### ISSUE TITLE
Account takeover

### ISSUE THREAD

**Issue by wnewlad** [cc-d/ieddit#90] opened 2019-10-29 06:01 UTC
Browsing around the site randomly can lead you to “becoming” another user giving access to their pm’s, subs, etc.

**Comment by wnewlad** [comment] 2019-10-29 06:19
https://stackoverflow.com/q/26668355 Interesting. They talk about caching and users using vpn which was caching cookies. So culprits are built in caching and cloudflare.

**Comment by wnewlad** [comment] 2019-10-29 09:26
A session can be taken over by replacing the cookie with another users. 
![06807573-D9AF-4117-9707-F568D1F09BB1](https://user-images.githubusercontent.com/56266673/67754297-9ce02e80-fa0c-11e9-961c-896e8ff87719.png)
Something for some reason is setting the wrong session cookie. 
https://imgur.com/a/Gz1oIdK

**Comment by cc-d** [comment] 2019-11-11 12:13
fixed with the removal of server side sessions.

bug was caused by a race condition w/ flask-session assigning random sessions to random users, causing the cookie to be overwritten on the end of request.

**Closed as completed by cc-d** 2019-11-11 12:13 UTC
